[build-system]
requires = ["jupyter_packaging~=0.9"]
build-backend = "jupyter_packaging.build_api"

[tool.jupyter-packaging.builder]
factory = "jupyter_packaging.npm_builder"

[tool.check-manifest]
ignore = ["tbump.toml", ".*", "*.yml", "package-lock.json", "bootstrap*", "conftest.py"]

[tool.pytest.ini_options]
addopts = "--doctest-modules"
testpaths = [
    "tests/"
]
timeout = 300
timeout_method = "thread"
filterwarnings= [
  # Fail on warnings
  "error",

  # Workarounds for https://github.com/pytest-dev/pytest-asyncio/issues/77
  "ignore:unclosed <socket.socket:ResourceWarning",
  "ignore:unclosed event loop:ResourceWarning",

  # Workaround for https://github.com/tornadoweb/tornado/issues/3106
  # (To be fixed in Tornado 6.2)
  "ignore:There is no current event loop:DeprecationWarning:tornado",

  # Workaround for distutils.Version used in ipykernel
  "ignore:The distutils package is deprecated and slated for removal:DeprecationWarning:ipykernel",

  # ZMQ uses Future internally, which raises a DeprecationWarning
  # When there is no loop running.
  # We could eventually find a way to make sure these are only created
  # when there is a running event loop.
  "ignore:There is no current event loop:DeprecationWarning:zmq",

  # Workaround for https://github.com/jupyter/nbformat/issues/232
  "ignore:Passing a schema:DeprecationWarning:nbformat",
]

[tool.jupyter-releaser]
skip = ["check-links"]

[tool.tbump.version]
current = "1.14.0.dev0"
regex = '''
  (?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)
  ((?P<channel>a|b|rc|.dev)(?P<release>\d+))?
'''

[tool.tbump.git]
message_template = "Bump to {new_version}"
tag_template = "v{new_version}"

[[tool.tbump.file]]
src = "jupyter_server/_version.py"
version_template = '({major}, {minor}, {patch}, "{channel}", "{release}")'

[[tool.tbump.field]]
name = "channel"
default = ""

[[tool.tbump.field]]
name = "release"
default = ""
